# npm install eslint --save-dev
# npx eslint --init
env:
  browser: true
  es6: true
  jquery: true
  es2021: true
  # FIXME: For Tamper Monkey
  greasemonkey: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules: {}
