# Use an official Node.js image as a parent image
FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm

# Install npm package repomix
RUN npm install -g repomix

# Set the working directory in the container
WORKDIR /workspace